# Generated by Django 4.2.3 on 2023-07-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('cerveja', models.CharField(max_length=20, null=True)),
                ('refrigerante', models.CharField(max_length=20, null=True)),
                ('espetinho', models.CharField(max_length=20, null=True)),
                ('cervejaQtd', models.IntegerField(null=True)),
                ('refrigeranteQtd', models.IntegerField(null=True)),
                ('espetinhoQtd', models.IntegerField(null=True)),
                ('cervejaPrecoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refrigerantePrecoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espetinhoPrecoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
