# Generated by Django 4.2.3 on 2023-07-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='cervejaPrecoTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='espetinhoPrecoTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='refrigerantePrecoTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
