# Generated by Django 4.2.3 on 2023-07-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0002_alter_comanda_cervejaprecototal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='precoTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
