# Generated by Django 4.2.3 on 2023-07-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0003_alter_comanda_precototal'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='listaItensSelecionados',
            field=models.TextField(null=True),
        ),
    ]
