# Generated by Django 4.2.3 on 2023-08-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0007_alter_comanda_listaitensselecionados'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
